#!/usr/bin/env python3
"""One-command preflight for a benchmark run (local AND cloud).

WHY THIS EXISTS
---------------
Starting a cell requires ~6 checks that were previously scattered across
RUNBOOK §0/§2.1/§7 and the workspace AGENTS.md. Doing them by hand costs an
operator (or an agent) a long, error-prone discovery pass every single time,
and the most important check — asserting the bench MCP identity at the seam —
was effectively undiscoverable because `/v1/identity/pubkeys` is bearer-gated
and returns `{"status":"error","error":"unauthorized"}` to a plain curl.

Run this instead. It prints a GO / NO-GO verdict and, on GO, the exact
launch command with `< /dev/null` and the flag ordering already correct.

Local cell (default — the resident model behind the :4545 relay proxy;
`--model` is a bench alias from WORKER_MODEL_REGISTRY):

    .venv/bin/python scripts/bench_preflight.py --model qwen3.6-35b-a3b-bench

Cloud cell (direct-to-cloud via OrcaRouter; `--model` is the MODEL HALF of
the '{provider}/{model}' roster key, not a bench alias):

    .venv/bin/python scripts/bench_preflight.py --cloud --provider deepseek --model deepseek-chat

Exit codes: 0 = GO, 1 = NO-GO (a blocking check failed).

This script only READS and reports. It never archives, wipes, launches, or
mutates anything — those stay operator decisions (RUNBOOK §0 step 3a, §2).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import re
import shutil
import socket
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# THE ONE SANCTIONED REBUILD. Named identically everywhere a check tells an
# operator to rebuild, because it is the only build that records what the image
# was made from — see harness/worker_image.py.
REBUILD_CMD = (
    "rebuild: press REBUILD WORKER on the board, "
    "or .venv/bin/python scripts/rebuild_worker_image.py"
)

# ── WHICH BUTTON FIXES THIS ─────────────────────────────────────────────────
#
# A refusal that names a shell command sends the operator to a terminal, and an
# operator sent to a shell for one thing ends up doing everything there — the
# same reasoning that moved the rebuild onto the board in the first place. So a
# failure that a custom tool repairs says WHICH TOOL, by id, and the board turns
# that into the button.
#
# IDS, NOT NAMES. The tool registry (control/tools.mjs + the dev manifest) is the
# only thing that knows a tool's display name and whether it is registered here
# at all — `bench-ready` and `bench-mcp-restart` are dev-contributed and absent
# from a bare clone of bench/. An id that resolves to nothing degrades to the
# text remedy already in the detail line, which is why every detail below still
# names its own fix in words.
TOOL_WORKER_REBUILD = "worker-image-rebuild"
TOOL_BENCH_READY = "bench-ready"
TOOL_BENCH_MCP_RESTART = "bench-mcp-restart"

# The expected served identity is DERIVED at check time, never hardcoded: the
# shared helper dev/scripts/lib.sh (`bench-identity-ed-fp`) is the
# single source of derivation — it loads the bench identity root seed (env
# OKP_BENCH_MCP_SEED, else 0600 file
# ~/.okp/bench/bench-identity-seed.txt, generated by bench-mcp.sh start
# if absent) and computes fp(ed_pubkey_bytes) via the canonical client
# crypto build.
# Both sides hash RAW ED PUBKEY BYTES — NOT fp(seed_bytes), which is a
# DIFFERENT value for the same identity. Comparing a fingerprint without
# naming its hashed input is how a real identity mismatch got wrongly
# dismissed once already. Identity is asserted AT THE SEAM; liveness is not
# identity; :4450 (operator host MCP) is forbidden.
LIB_SH = REPO.parent / "dev" / "scripts" / "lib.sh"

# :4450 is the operator's REAL host client (interactive keychain identity).
# Pointing any bench component at it mints orgs under the operator's identity
# and the run dies ~30s later with "leader membership did not include org_id".
FORBIDDEN_PORT = 4450


class Check:
    def __init__(self) -> None:
        self.rows: list[tuple[str, bool, str, bool, str | None]] = []

    def add(
        self,
        name: str,
        ok: bool,
        detail: str,
        blocking: bool = True,
        remedy: str | None = None,
    ) -> None:
        """Record one check.

        ``remedy`` names the CUSTOM TOOL that repairs this failure, by tool id.
        It is set per FAILURE BRANCH, never per check name: "the worker image is
        stale" is repaired by pressing Rebuild worker, but "docker not on PATH"
        is the same check failing for a reason no button can fix, and offering
        one there would be a lie the operator pays for by pressing it.

        The id is all that is emitted. The tool's NAME, and whether it is
        registered at all, are resolved by the control plane from the tool
        registry — this file must not carry a second copy of either, and a bare
        clone of bench/ genuinely does not have the dev-contributed tools.
        """
        self.rows.append((name, ok, detail, blocking, remedy))

    @property
    def blocking_failures(self) -> list[tuple[str, bool, str, bool, str | None]]:
        return [r for r in self.rows if not r[1] and r[3]]

    def as_rows(self) -> list[dict]:
        """The same rows, as data.

        The board renders preflight rather than re-deriving it: two
        implementations of "can I start" is how a dashboard ends up disagreeing
        with the CLI about why a button is dead. One check, two renderings.
        """
        return [
            {
                "name": name,
                "ok": ok,
                "blocking": blocking,
                "status": "pass" if ok else ("fail" if blocking else "warn"),
                "detail": detail,
                # Only on a failure. A passing row with a remedy attached would
                # invite a press that changes a bench that was already correct.
                "remedy_tool": None if ok else remedy,
            }
            for name, ok, detail, blocking, remedy in self.rows
        ]

    def render(self) -> None:
        width = max(len(r[0]) for r in self.rows)
        for name, ok, detail, blocking, _remedy in self.rows:
            mark = "PASS" if ok else ("FAIL" if blocking else "WARN")
            print(f"  [{mark}] {name.ljust(width)}  {detail}")


def port_open(port: int, host: str = "127.0.0.1", timeout: float = 2.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def check_ports(c: Check) -> None:
    for port, what in ((4545, "local relay"), (4550, "bench MCP"), (4440, "hub")):
        ok = port_open(port)
        hint = "" if ok else "  -> see RUNBOOK §7 for bring-up"
        # Only the bench MCP has a button of its own. The relay and the hub are
        # brought up with the stack, and pointing at Restart MCP for a dead hub
        # would send the operator to press something that cannot help.
        c.add(
            f"port {port} ({what})",
            ok,
            ("open" if ok else "CLOSED") + hint,
            remedy=TOOL_BENCH_MCP_RESTART if port == 4550 else None,
        )


def expected_bench_ed_fp() -> str:
    """Expected bench identity fp from the shared helper — the ONLY derivation seam.

    Never re-derive seed -> pubkey -> fp in this file: lib.sh owns the
    derivation (seed -> client dist/crypto.js -> fp). Raises RuntimeError
    on ANY failure (missing seed, missing crypto build, empty output): an
    underivable expected identity is a HARD failure, never a skip
    (AGENTS.md §2.1).
    """
    proc = subprocess.run(
        ["bash", str(LIB_SH), "bench-identity-ed-fp"],
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    out = proc.stdout.strip()
    if proc.returncode != 0 or not out:
        raise RuntimeError(f"rc={proc.returncode} stderr={proc.stderr.strip() or '-'}")
    return out


def check_identity(c: Check) -> None:
    """Assert identity AT THE SEAM. Liveness is not identity (AGENTS.md §2.1).

    A port answering and health returning 200 proved nothing in two separate
    real failures. Anything that mints, signs, or attributes must have its
    identity asserted, never inferred.
    """
    try:
        sys.path.insert(0, str(REPO))
        from harness.lifecycle.lconfig import LifecycleConfig
        from harness.lifecycle.mcp_rest import McpRest
    except Exception as exc:  # noqa: BLE001
        c.add("identity assertion", False, f"cannot import lifecycle client: {exc}")
        return

    logging.basicConfig(level=logging.CRITICAL)
    log = logging.getLogger("preflight")
    cfg = LifecycleConfig()

    for label, url in (("bench", cfg.leader_mcp_url),):
        if f":{FORBIDDEN_PORT}" in url:
            c.add(
                f"identity {label}",
                False,
                f"{url} TARGETS THE OPERATOR HOST MCP :{FORBIDDEN_PORT} — "
                "this mints orgs under the operator's keychain identity. "
                "See AGENTS.md §2.1.",
            )
            continue
        try:
            expected = expected_bench_ed_fp()
        except Exception as exc:  # noqa: BLE001
            c.add(
                f"identity {label}",
                False,
                f"cannot derive expected fp via {LIB_SH}: {exc} — HARD failure; "
                "make the bench identity seed available (env OKP_BENCH_MCP_SEED or "
                "0600 ~/.okp/bench/bench-identity-seed.txt; run bench-mcp.sh start to generate it)",
            )
            continue
        try:
            payload = McpRest(url, cfg, log).identity_pubkeys()
            ed = (
                payload.get("ed25519")
                or payload.get("ed25519_pubkey")
                or payload.get("edPubkey")
                or ""
            )
            fp = hashlib.sha256(bytes.fromhex(ed)).hexdigest()[:8] if ed else ""
            if not fp:
                c.add(
                    f"identity {label}",
                    False,
                    f"{url} no ed25519 key in response",
                    remedy=TOOL_BENCH_MCP_RESTART,
                )
            elif fp == expected:
                c.add(f"identity {label}", True, f"{url} fp(ed_pubkey)={fp}")
            else:
                c.add(
                    f"identity {label}",
                    False,
                    f"{url} fp(ed_pubkey)={fp} EXPECTED {expected} — wrong identity "
                    "on the seam; a run on an unverified seam is VOID-INSTRUMENT "
                    "(RUNBOOK §6)",
                    remedy=TOOL_BENCH_MCP_RESTART,
                )
        except Exception as exc:  # noqa: BLE001
            # Unreachable is a HARD failure, never a skip (AGENTS.md §2.1).
            c.add(
                f"identity {label}",
                False,
                f"{url} UNREACHABLE/failed: {exc}",
                remedy=TOOL_BENCH_MCP_RESTART,
            )


def check_image(c: Check) -> None:
    """Is the worker image built from the source on disk?

    ASKED AS A CONTENT QUESTION, not a timestamp one. This check used to compare
    the newest mtime under images/worker against the image's .Created, and it
    could not be cleared: re-saving a file without changing a byte bumps its
    mtime, the rebuild is a full cache hit, the image id and its creation time
    never move, and the check stays red through every rebuild. The operator
    presses REBUILD, a real build succeeds, and nothing changes — indistinguish-
    able from a dead button.

    So the build bakes a digest of its own source (harness/worker_image.py) and
    this reads it back. The vendored opencode plugin is baked in at build time,
    so a genuinely stale image runs stale plugin code with nothing to say so.
    """
    if shutil.which("docker") is None:
        c.add("worker image", False, "docker not on PATH")
        return

    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))
    from harness.worker_image import (
        IMAGE,
        configured_plugin_dir,
        image_digest,
        source_digest,
    )

    baked = image_digest(IMAGE)
    if baked is None:
        c.add(
            "worker image",
            False,
            f"{IMAGE} MISSING -> {REBUILD_CMD}",
            remedy=TOOL_WORKER_REBUILD,
        )
        return

    # THE QUESTION IS "would this installation build this image", not "would a
    # vanilla build produce it". The plugin is baked in at build time and is part
    # of the source digest, so a checker that ignores the seam flags every
    # plugin-bearing image as stale — which it did, on every dev build, blocking
    # a preflight that had nothing actually wrong with it. Unset seam (a bare
    # clone) still asks the vanilla question, unchanged.
    plugin_dir = configured_plugin_dir()
    want = source_digest(REPO / "images" / "worker", plugin_dir=plugin_dir)
    if not baked:
        # Built by a bare `docker build`, which records nothing about its source.
        # Reported as its own case: "we cannot tell" is not "it is current".
        c.add(
            "worker image",
            False,
            f"{IMAGE} carries no source digest — it was not built by the rebuild "
            f"path, so nothing recorded what it was built from -> {REBUILD_CMD}",
            remedy=TOOL_WORKER_REBUILD,
        )
        return

    ok = baked == want
    # NAME WHICH BUILD WAS COMPARED. "Stale" against the wrong question is the
    # failure this check just had, and an operator reading it could not tell.
    flavour = "with the configured plugin" if plugin_dir else "vanilla (no plugin configured)"
    c.add(
        "worker image",
        ok,
        f"built from source {baked[:12]}"
        + (
            f" but images/worker {flavour} is now {want[:12]} -> {REBUILD_CMD}"
            if not ok
            else f" — matches images/worker byte for byte, {flavour}"
        ),
        remedy=TOOL_WORKER_REBUILD,
    )


def check_grader_image(c: Check) -> None:
    """Is the grading image built, and current with the gates on disk?

    Grading runs ONLY in this image — same digest-pinned Node the candidate is
    built against, toolchain installed from the lockfile. A missing image aborts
    the run rather than falling back to the host, so catching it here turns a
    mid-campaign abort into a line the operator can act on before starting.

    Staleness is a content question, exactly as it is for the worker image: a
    digest of the source is baked in at build time and read back. A stale image
    grades against gate code that is not the code on disk, and nothing in the
    report would say so.
    """
    if shutil.which("docker") is None:
        c.add("grader image", False, "docker not on PATH")
        return
    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))
    from harness.grader_image import IMAGE, image_digest, source_digest

    gates = REPO / "grader"
    dockerfile = REPO / "images" / "grader" / "Dockerfile"
    baked = image_digest(IMAGE)
    if baked is None:
        c.add(
            "grader image",
            False,
            f"{IMAGE} is not built (or carries no source digest). "
            "Build: python3 scripts/rebuild_grader_image.py",
        )
        return
    live = source_digest(gates, dockerfile)
    if baked != live:
        c.add(
            "grader image",
            False,
            f"{IMAGE} is STALE — built from {baked[:12]}, gates on disk are {live[:12]}. "
            "It would grade against gate code that is not the code on disk. "
            "Rebuild: python3 scripts/rebuild_grader_image.py",
        )
        return
    c.add("grader image", True, f"{IMAGE} current ({live[:12]})")


def check_grader_resources(c: Check) -> None:
    """Can grading actually fit on this machine right now?

    ASKED OF THE CONTAINER, never of this host: only the container knows what it
    has been given, and the answer changes with whatever else is running. It is
    sized against FREE cpu and memory, not total — the operator may already have
    containers up, and a worker count derived from the total would start
    browsers into memory that is already spoken for.

    Caught HERE because the alternative is an OOM kill part-way through a
    grading pass, and an OOM kill is recorded as gates failing: a machine that
    was busy, certified as a candidate that was wrong.
    """
    if shutil.which("docker") is None:
        c.add("grader resources", False, "docker not on PATH")
        return
    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))
    from harness.grader_image import IMAGE, image_digest

    if image_digest(IMAGE) is None:
        # The image row above already says this, in the words that fix it.
        c.add("grader resources", False, "not asked — the grading image is not built")
        return
    try:
        out = subprocess.run(  # noqa: S603 - fixed argv
            ["docker", "run", "--rm", IMAGE, "--resources"],
            capture_output=True,
            text=True,
            check=False,
            timeout=120,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        c.add("grader resources", False, f"could not ask the grading image: {exc}")
        return

    detail = (out.stdout or "").strip().splitlines()
    summary = detail[-1] if detail else "no answer"
    if out.returncode != 0:
        reason = (out.stderr or "").strip().splitlines()
        c.add("grader resources", False, reason[-1] if reason else summary)
        return
    c.add("grader resources", True, summary)


def check_self_compact_tool(c: Check, args) -> None:
    """Prove the worker image ACTUALLY wires the self-compact plugin.

    WHY THIS NEEDS PROVING (2026-09-03). opencode SWALLOWS PLUGIN LOAD ERRORS: a
    deliberately corrupted `plugin.ts` produces no output at all — the serve
    starts, answers health, and simply has no plugin. So every negative signal
    an operator would look for is absent by construction, and a stale or broken
    image would run a whole cell with the plugin missing and nothing to say so.
    Every chunk boundary would then abort the cell on no_compaction_evidence
    with nothing anywhere saying the plugin was the reason.

    Liveness is not wiring (AGENTS.md 2.1). The restored mechanism is the
    worker-side self-fire plugin (self-compact.ts), loaded via the opencode
    `config.plugin` array baked into the image — so this asserts that wiring
    BY NAME from the image's own baked config, plus that the file exists at
    the wired path, rather than inferring it from a clean startup.

    Only meaningful when the run will actually ask for compaction — checked when
    `--compact` is passed, skipped otherwise with that stated.
    """
    if not getattr(args, "compact", False):
        c.add(
            "self-compact wiring",
            True,
            "not checked — this run does not use compaction (--compact absent)",
        )
        return
    if shutil.which("docker") is None:
        c.add("self-compact wiring", False, "docker not on PATH")
        return

    # Read the image's own baked opencode config and ask it — no serve, no
    # env: wiring is a property of the image, not of a runtime session.
    probe = (
        "const fs=require('fs');"
        "const cfg=JSON.parse(fs.readFileSync("
        "'/etc/xdg/opencode/opencode.json','utf8'));"
        "const plugs=(cfg.plugin||[]).filter(function(p){"
        "return /self-compact\\.ts$/.test(String(p))});"
        "const ok=plugs.length>0&&plugs.every(function(p){"
        "return fs.existsSync(String(p))});"
        # A2: the wired file must be the PHASE-GATED arm. A stale image can be
        # correctly wired to the OLD plugin, which fires on the marker alone and
        # leaks a compaction into the repair phase — the exact defect this
        # check now has to be able to see. Grep the baked source for the
        # sentinel env name; wiring alone was never proof of behaviour.
        "const gated=ok&&plugs.every(function(p){"
        "return fs.readFileSync(String(p),'utf8')"
        ".indexOf('OKP_COMPACT_PHASE_FILE')>=0});"
        "console.log(JSON.stringify({wired:plugs,exist:ok,gated:gated}))"
    )
    proc = subprocess.run(
        [
            "docker", "run", "--rm",
            "--entrypoint", "node", "okp-bench-worker:v1", "-e", probe,
        ],
        capture_output=True, text=True, check=False, timeout=180,
    )
    tail = (proc.stdout or "").strip().splitlines()
    wired: list = []
    exist = False
    gated = False
    if tail:
        try:
            verdict = json.loads(tail[-1])
            wired = verdict.get("wired") or []
            exist = bool(verdict.get("exist"))
            gated = bool(verdict.get("gated"))
        except (ValueError, AttributeError):
            pass
    present = bool(wired) and exist
    c.add(
        "self-compact wiring",
        present,
        f"self-compact.ts is wired in the image's opencode config ({wired[0]})"
        if present
        else (
            "self-compact.ts is NOT wired in the image's baked opencode config "
            "(or the file is missing at the wired path) -> the --compact flag "
            "arms a plugin that is not loaded, and every chunk boundary will "
            "abort the cell on no_compaction_evidence. Rebuild: docker build "
            "-t okp-bench-worker:v1 images/worker "
            "--build-context okp-sidecar=images/sidecar"
        ),
        remedy=TOOL_WORKER_REBUILD,
    )
    c.add(
        "self-compact phase gate",
        present and gated,
        "the baked plugin reads the harness phase sentinel "
        "(OKP_COMPACT_PHASE_FILE) — repair rounds cannot compact"
        if (present and gated)
        else (
            "the baked self-compact.ts does NOT read OKP_COMPACT_PHASE_FILE -> "
            "this image carries the PRE-FIX arm, which fires on the CHUNK "
            "FINISHED marker alone and leaks a compaction into the repair "
            "phase (run 1788462647). Rebuild: docker build -t "
            "okp-bench-worker:v1 images/worker "
            "--build-context okp-sidecar=images/sidecar"
        ),
        remedy=TOOL_WORKER_REBUILD,
    )


def check_control_plane_freshness(c: Check) -> None:
    """Is the RUNNING control plane older than the control-plane source?

    THE FAILURE THIS EXISTS FOR (2026-09-02). The control plane is a long-lived
    HOST process, and `make control-start` is a deliberate no-op when :7718 is
    already listening — so `make up` never restarts it. A compaction launch ran
    with the flag present in `control/server.mjs` and absent from the argv the
    running process built, because that process had been up since before the
    edit. The run looked completely normal: no error, no warning, just a cell
    that quietly did not compact.

    SAME DISCIPLINE AS THE WORKER IMAGE. That check compares the image's build
    time against the newest file baked into it; this compares the process's
    start time against the newest file it would have parsed. A process cannot
    report which version of a file it read, but it can report when it started,
    and a start that predates the source proves the source is not what is
    running.

    BLOCKING. A stale control plane does not corrupt a run after launch — it
    shapes the argv AT launch and nothing after — but that is precisely the
    damage: the cell runs to completion, looks entirely normal, and measured
    something other than what was configured. The bench fails loud and aborts
    rather than salvaging; a run launched from a process that is not this code
    is exactly the kind of quietly-different experiment that rule exists for.

    This is self-diagnosing by construction: the board asks the control plane
    for preflight, so a stale control plane runs the check that names its own
    staleness and refuses the launch.

    DOWN IS NOT STALE, and is not a failure here — see below.
    """
    control_dir = REPO / "control"
    if not control_dir.is_dir():
        c.add("control plane", True, "no control/ directory — CLI-only bench")
        return

    newest = 0.0
    newest_path = ""
    for path in control_dir.rglob("*.mjs"):
        if not path.is_file() or path.name.endswith(".test.mjs"):
            continue
        mtime = path.stat().st_mtime
        if mtime > newest:
            newest, newest_path = mtime, str(path.relative_to(REPO))

    try:
        with urllib.request.urlopen(
            "http://127.0.0.1:7718/api/health", timeout=3
        ) as resp:
            health = json.loads(resp.read().decode("utf-8"))
    except Exception:  # noqa: BLE001 - any failure to reach it means it is down
        # DOWN IS NOT STALE. A board-launched run cannot start at all without
        # it, and a CLI run does not need it; either way "not running" is a
        # different fact from "running old code" and must not be reported as one.
        c.add(
            "control plane",
            True,
            "not running on :7718 — board launches unavailable "
            "(start: cd dev && make control-start)",
        )
        return

    ok, detail = control_plane_freshness_verdict(
        started_at=str(health.get("started_at") or ""),
        newest_mtime=newest,
        newest_path=newest_path,
    )
    # PREPARE BENCH, not Rebuild worker. Staleness here means the long-lived
    # host process is running code older than control/ on disk, and the only
    # tool that cycles it is bench-ready — which deliberately restarts it LAST,
    # because a process cannot supervise its own replacement.
    c.add("control plane", ok, detail, remedy=TOOL_BENCH_READY)


def control_plane_freshness_verdict(
    *, started_at: str, newest_mtime: float, newest_path: str
) -> tuple[bool, str]:
    """The decision, split out so it can be tested without a live service.

    Returns ``(ok, detail)``. Three cases, and the middle one is the one that
    actually fired: a control plane old enough to have no ``started_at`` field
    cannot be newer than the source that introduced the field, so it is stale by
    definition rather than by comparison.
    """
    if not started_at:
        return (
            False,
            "running, but reports no started_at — it predates the freshness "
            "field entirely, so it is DEFINITELY stale -> cd dev && make control-restart",
        )

    import datetime as _dt

    started_ts = _dt.datetime.fromisoformat(
        started_at.replace("Z", "+00:00")
    ).timestamp()
    stale = newest_mtime > started_ts
    return (
        not stale,
        f"started {started_at[:19]}"
        + (
            f" but {newest_path} is NEWER -> the running process is not this "
            "code; restart: cd dev && make control-restart"
            if stale
            else " (newer than control/ — no restart needed)"
        ),
    )


def check_serve_drive_image(c: Check) -> None:
    """Prove the worker image can serve the :4096 live-view data path.

    The live view (opencode serve over host :4096) is carried by the egress
    sidecar's ingress forward, which the cell reaches over the --internal net
    (WO-25). A worker image built BEFORE that fix bakes an egress-sidecar.js
    WITHOUT the ingress forward, so host :4096 silently serves nothing and the
    harness quietly falls back to the deadlock-prone stdout drive. Liveness is
    not wiring (AGENTS.md §2.1): instead of trusting the image timestamp, read
    the baked sidecar and assert the ingress-forward capability is present.
    """
    if shutil.which("docker") is None:
        c.add("serve-drive image", False, "docker not on PATH")
        return
    proc = subprocess.run(
        [
            "docker",
            "run",
            "--rm",
            "--entrypoint",
            "cat",
            "okp-bench-worker:v1",
            "/opt/okp/egress-sidecar.js",
        ],
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "").strip().splitlines()
        c.add(
            "serve-drive image",
            False,
            "cannot read baked egress-sidecar.js: "
            + (detail[-1][:160] if detail else f"exit {proc.returncode}"),
            remedy=TOOL_WORKER_REBUILD,
        )
        return
    if "OKP_INGRESS_CELL_HOST" in proc.stdout:
        c.add(
            "serve-drive image",
            True,
            "baked egress-sidecar.js carries the :4096 ingress forward "
            "(OKP_INGRESS_CELL_HOST present)",
        )
    else:
        c.add(
            "serve-drive image",
            False,
            "baked egress-sidecar.js LACKS the :4096 ingress forward — image "
            "predates the sidecar-ingress fix (137b025); " + REBUILD_CMD,
            remedy=TOOL_WORKER_REBUILD,
        )


# ── cloud / local model + campaign-slot checks ──────────────────────────────
#
# These mirror the harness's own gates so preflight fails with the SAME words
# run_cumulative.py would exit 2 with, instead of letting the operator discover
# them after a launch: `_compose_cloud_slug` (cloud roster membership),
# `_apply_model_override` (local registry + retired aliases), and
# control/campaign.mjs `campaignTargetFor` (where a campaign lands).


def _segment(value: str, fallback: str) -> str:
    """Mirror of control/tree.mjs `segment()`: dots read as the archive
    convention and slashes as depth, so both (and backslashes) become dashes;
    empty input yields a NAMED placeholder, never an empty segment."""
    cleaned = re.sub(r"[./\\]+", "-", str(value or "").strip()).strip("-")
    return cleaned or fallback


def _campaign_dir_name(model: str) -> str:
    """Mirror of control/campaign.mjs `campaignDirName()` — the LEGACY flat
    slot `runs/cumulative-<model>`, reached only when no tree pointer exists."""
    return "cumulative-" + re.sub(r"[./]", "-", str(model))


def _read_tree_pointer(runs_root: Path) -> tuple[str | None, str | None]:
    """Read runs/active-tree.json READ-ONLY. Returns (tree_id, error).

    Mirrors control/tree.mjs `readTreePointer`: an ABSENT pointer means
    "legacy flat layout", but a MALFORMED one is an error, never an absent —
    guessing would route a campaign into the wrong tree.
    """
    pointer = runs_root / "active-tree.json"
    if not pointer.exists():
        return None, None
    try:
        raw = json.loads(pointer.read_text(encoding="utf-8"))
        active = str(raw.get("active", "") if isinstance(raw, dict) else "")
        if not re.fullmatch(r"\d{9,11}", active):
            raise ValueError(f"active={active!r} is not a unix-seconds tree id")
        return active, None
    except Exception as exc:  # noqa: BLE001
        return None, f"active-tree.json present but unreadable: {exc}"


def check_cloud_key(c: Check, spend_key) -> None:
    """Blocking when --cloud. Mirrors spend_key.resolve_cloud_api_key: env
    ORCAROUTER_API_KEY wins, else the dotenv key file (config/cloud.env,
    override OKP_BENCH_CLOUD_KEY_FILE). Reports present + source +
    fingerprint ONLY — the key value is never printed (R-37). Never creates
    the file."""
    if spend_key is None:
        c.add("cloud key", False, "skipped — harness import failed")
        return
    try:
        token = spend_key.resolve_cloud_api_key()
    except Exception as exc:  # noqa: BLE001 — SpendKeyError names the checked paths
        c.add("cloud key", False, f"ABSENT — {exc}")
        return
    # Source label follows the module's documented precedence (env export wins).
    if os.environ.get(spend_key.CLOUD_API_KEY_ENV, "").strip():
        source = f"env:{spend_key.CLOUD_API_KEY_ENV}"
    else:
        source = f"file:{spend_key.resolve_cloud_key_file()}"
    fp = spend_key.key_fingerprint(token)
    c.add(
        "cloud key", True, f"present source={source} fp={fp} (key value never printed)"
    )


def check_cloud_model(c: Check, bench_config, args) -> None:
    """Blocking when --cloud. Mirrors `_compose_cloud_slug`: `{provider}/{model}`
    must be a key of CLOUD_ORCAROUTER_PROVIDER['models'] (the harness ACCEPT
    list); the composed slug is `{router}/{provider}/{model}`."""
    if bench_config is None:
        c.add("cloud model", False, "skipped — harness import failed")
        return
    provider = str(args.provider or "").strip()
    model = str(args.model or "").strip()
    if not provider or not model:
        c.add(
            "cloud model",
            False,
            "--cloud requires --provider <vendor> and --model <model> "
            "(run_cumulative.py exits 2)",
        )
        return
    router = str(args.router or bench_config.DEFAULT_CLOUD_ROUTER).strip()
    model_key = f"{provider}/{model}"
    cloud_models = bench_config.CLOUD_ORCAROUTER_PROVIDER.get("models", {})
    if model_key not in cloud_models:
        available = sorted(cloud_models)
        sample = ", ".join(available[:8])
        c.add(
            "cloud model",
            False,
            f"--cloud model {model_key!r} is not in the OrcaRouter provider block "
            f"({len(available)} accepted keys; e.g. {sample}, … — full list: "
            "harness/config.py CLOUD_ORCAROUTER_PROVIDER). "
            "run_cumulative.py exits 2 for this.",
        )
        return
    entry = cloud_models[model_key]
    limit = entry.get("limit", {}) if isinstance(entry, dict) else {}
    c.add(
        "cloud model",
        True,
        f"slug={router}/{model_key} name={entry.get('name', '?')!r} "
        f"context={limit.get('context')} output={limit.get('output')}",
    )


def check_local_model(c: Check, bench_config, args) -> None:
    """Blocking in local mode. Mirrors `_apply_model_override`: the alias must be
    in WORKER_MODEL_REGISTRY, and RETIRED_MODEL_ALIASES are refused by their
    RETIREMENT reason, not as 'unknown' (a spelled-right name is not a typo)."""
    if bench_config is None:
        c.add("local model", False, "skipped — harness import failed")
        return
    registry = getattr(bench_config, "WORKER_MODEL_REGISTRY", {})
    retired = getattr(bench_config, "RETIRED_MODEL_ALIASES", {})
    available = ", ".join(sorted(k for k in registry if k not in retired)) or "none"
    alias = str(args.model or "").strip()
    if alias.startswith("local-llm-proxy/"):
        alias = alias[len("local-llm-proxy/") :]
    if not alias:
        c.add(
            "local model",
            False,
            "--model is required — the auto-resident roster rung is retired. "
            f"available aliases: {available}",
        )
        return
    if alias in retired:
        c.add(
            "local model",
            False,
            f"--model {args.model!r} — {retired[alias]} available aliases: {available}",
        )
        return
    if alias not in registry:
        c.add(
            "local model",
            False,
            f"--model {args.model!r} is not a known worker model alias. "
            f"available aliases: {available}",
        )
        return
    limit = registry[alias].get("limit", {})
    c.add(
        "local model",
        True,
        f"alias={alias} ({registry[alias].get('name', '?')}) "
        f"context={limit.get('context')} output={limit.get('output')}",
    )


_MJS_KEY_RE = re.compile(r'^\s*"([^"]+/[^"]+)":\s*\{', re.M)


def _read_mirror_keys() -> set[str]:
    """Keys of control/cloud.mjs CLOUD_MODELS, bounded by the object's closing
    `};` so nothing else in the file can match."""
    text = (REPO / "control" / "cloud.mjs").read_text(encoding="utf-8")
    start = text.index("export const CLOUD_MODELS = {")
    end = text.index("\n};", start)
    return set(_MJS_KEY_RE.findall(text[start:end]))


def check_roster_drift(c: Check, bench_config) -> None:
    """NON-BLOCKING in both modes: config.py CLOUD_ORCAROUTER_PROVIDER['models']
    is CANONICAL; control/cloud.mjs CLOUD_MODELS is a deliberate mirror the
    control plane serves. The mirror is known to lag — drift is a surfaced
    defect, not a gate on launching."""
    if bench_config is None:
        c.add("roster drift", False, "skipped — harness import failed", blocking=False)
        return
    config_keys = set(bench_config.CLOUD_ORCAROUTER_PROVIDER.get("models", {}))
    try:
        mirror_keys = _read_mirror_keys()
    except Exception as exc:  # noqa: BLE001
        c.add(
            "roster drift",
            False,
            f"could not parse control/cloud.mjs CLOUD_MODELS: {exc}",
            blocking=False,
        )
        return
    if config_keys == mirror_keys:
        c.add(
            "roster drift",
            True,
            f"config.py and control/cloud.mjs agree ({len(config_keys)} keys)",
        )
        return
    parts = [
        f"config.py has {len(config_keys)} keys, control/cloud.mjs mirrors {len(mirror_keys)}"
    ]
    for label, diff in (
        ("missing in mirror", config_keys - mirror_keys),
        ("missing in config", mirror_keys - config_keys),
    ):
        if not diff:
            continue
        shown = sorted(diff)
        extra = f" +{len(shown) - 6} more" if len(shown) > 6 else ""
        parts.append(f"{label}: {', '.join(shown[:6])}{extra}")
    parts.append("config.py is canonical; mirror lag is a surfaced defect, not a gate")
    c.add("roster drift", False, " — ".join(parts), blocking=False)


def check_feedback_completeness(c: Check) -> None:
    """BLOCKING: every graded gate must have a human-written feedback override.

    WO-FEEDBACK-VOICE-3 (2026-08-30): the feedback voice is SINGLE-SYSTEM. There
    is NO title-derived fallback — `_humanize_check` raises
    `MissingFeedbackOverrideError` for a gate with no entry in
    `grader/feedback.json`, because the title-derived sentence
    (a test title) states the RULE and answers the gate's question for free.

    A missing override is therefore a misconfigured benchmark, not a graceful
    degradation. This check refuses to let a run start until every gate is
    covered. It is the launch half of the guarantee; the CI half is
    `test_every_gate_token_has_an_override`.
    """
    try:
        sys.path.insert(0, str(REPO))
        from harness.adapters.backgammon import missing_feedback_overrides
    except Exception as exc:  # noqa: BLE001
        c.add("feedback completeness", False, f"could not import harness: {exc}")
        return

    gates_dir = REPO / "grader"
    try:
        missing = sorted(missing_feedback_overrides(gates_dir))
    except Exception as exc:  # noqa: BLE001
        c.add(
            "feedback completeness",
            False,
            f"could not enumerate feedback overrides: {exc}",
        )
        return

    if not missing:
        c.add(
            "feedback completeness",
            True,
            "every graded gate has a human-written feedback override",
        )
        return

    shown = ", ".join(missing[:10])
    extra = f" (+{len(missing) - 10} more)" if len(missing) > 10 else ""
    c.add(
        "feedback completeness",
        False,
        f"NO-GO: {len(missing)} gate(s) lack a feedback override: "
        f"{shown}{extra}. Write a symptom sentence for each in "
        "grader/feedback.json before launching.",
    )


def check_run_dir(c: Check, args) -> None:
    """Report whether the chosen model's campaign slot is already occupied.

    READ-ONLY — never writes or deletes under runs/. Archive, never delete
    (RUNBOOK §0 3a); under the tree layout a reset MINTS a new tree rather
    than unlinking (control/tree.mjs).

    Slot resolution mirrors control/campaign.mjs `campaignTargetFor`: the
    active tree WINS when the pointer exists — cloud campaigns land at
    runs/<tree>/cloud/<router>/<provider>/<model>, local ones at
    runs/<tree>/local/local-llm-proxy/omlx/<model>; only a bench with NO
    pointer uses the legacy flat runs/cumulative-<model> slot.
    """
    runs_root = REPO / "runs"
    tree_id, tree_err = _read_tree_pointer(runs_root)
    if tree_err:
        c.add(
            "campaign slot",
            False,
            f"{tree_err} — refusing to guess which tree is live (control/tree.mjs)",
        )
        return
    if args.cloud:
        provider = str(args.provider or "").strip()
        model = str(args.model or "").strip()
        router = str(args.router or "orcarouter").strip()
        if tree_id:
            rel = (
                Path(tree_id)
                / "cloud"
                / _segment(router, "orcarouter")
                / _segment(provider, "unknown-provider")
                / _segment(model, "unknown-model")
            )
        else:
            rel = Path(_campaign_dir_name(f"{provider}/{model}"))
    else:
        alias = str(args.model or "").strip()
        if alias.startswith("local-llm-proxy/"):
            alias = alias[len("local-llm-proxy/") :]
        if tree_id:
            rel = (
                Path(tree_id)
                / "local"
                / "local-llm-proxy"
                / "omlx"
                / _segment(alias, "unknown-model")
            )
        else:
            rel = Path(_campaign_dir_name(alias))
    tree_note = (
        f"active tree {tree_id}" if tree_id else "no active tree — legacy flat layout"
    )
    slot = runs_root / rel
    if not slot.exists():
        c.add("campaign slot", True, f"{rel} ABSENT ({tree_note}) — clean slate")
        return
    stamp = "$(date +%Y%m%dT%H%M%S)"
    c.add(
        "campaign slot",
        False,
        f"{rel} EXISTS ({tree_note}) — a campaign occupies this slot. "
        "ARCHIVE IT, NEVER DELETE (legacy: mv runs/<dir> runs/<dir>.<why>-"
        f"{stamp}; tree layout: reset mints a NEW tree, never unlink). "
        "A launch into it RESUMES that campaign — intended only for resumes.",
    )


# ── the board's during-the-run surface ──────────────────────────────────────
#
# LIVENESS IS NOT WIRING (AGENTS.md §2.1). The board answering 200 on :7717
# proves nothing about whether its sources RESOLVE, exactly as a port answering
# proved nothing about identity. This asserts the SEAM instead: the reader's own
# resolver, invoked directly, against the streams actually on disk.
#
# THE DEFECT THIS EXISTS FOR (2026-08-29). LIVE-STREAM.md documents the stream
# at `runs/<run>/live.jsonl`, but the harness opens it in `run_cell` via
# `LiveStream.for_run(run_dir)` where `run_dir` is the CELL directory — so it
# lands at `<campaign>/memory<ARM>/cell-<seq>/live.jsonl`, one level below the
# campaign dir `activeRun()` resolves. Both dashboard readers joined the bare
# filename onto `run.dir` and opened a path that never exists, so the gate wall
# and the learning matrix sat empty for the entire life of every run while the
# harness appended to a file a few directories down.
#
# WHY NEITHER TEST SUITE CAUGHT IT, WHICH IS THE REAL LESSON. All 12 contract
# tests in tests/test_live_stream.py pass `tmp_path` to `for_run`; the reader's
# tests passed a synthetic directory to the reader. Each half was verified
# against a directory IT SUPPLIED, so both agreed in tests and disagreed on
# disk. A writer test and a reader test cannot find a disagreement about WHERE —
# only something that reads the writer's real output with the reader's real code
# can, and that is this check.
STREAM_SEAM_JS = """
import { activeRun, liveStreamPath } from './sources/_runtime.mjs';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';

// GROUND TRUTH, gathered WITHOUT the resolver — a check that used
// liveStreamPath to find what liveStreamPath should find proves nothing.
// Skips worktree/.git: the model's checkout is large and never holds a stream.
async function walk(dir, depth, hits) {
  if (depth > 4) return hits;
  let ents = [];
  try { ents = await fs.readdir(dir, { withFileTypes: true }); } catch { return hits; }
  for (const e of ents) {
    if (e.isFile() && e.name === 'live.jsonl') hits.push(join(dir, e.name));
    else if (e.isDirectory() && e.name !== '.git' && e.name !== 'worktree' && e.name !== 'node_modules') {
      await walk(join(dir, e.name), depth + 1, hits);
    }
  }
  return hits;
}

const runsRoot = process.env.SEAM_RUNS_ROOT;
const run = await activeRun(runsRoot);
const out = { run_dir: run?.dir ?? null, resolved: null, on_disk: [] };
if (run?.dir) {
  out.resolved = await liveStreamPath(run.dir);
  out.on_disk = await walk(run.dir, 0, []);
}
process.stdout.write(JSON.stringify(out));
"""


def check_live_stream(c: Check) -> None:
    """The board's reader must find the stream the harness actually writes."""
    dash = REPO / "dashboard"
    node = shutil.which("node")
    if node is None:
        c.add(
            "board live stream",
            True,
            "node not on PATH — reader seam unverified",
            blocking=False,
        )
        return
    if not (dash / "sources" / "_runtime.mjs").is_file():
        c.add(
            "board live stream",
            True,
            "dashboard sources absent — nothing to verify",
            blocking=False,
        )
        return

    proc = subprocess.run(
        [node, "--input-type=module", "-e", STREAM_SEAM_JS],
        capture_output=True,
        text=True,
        check=False,
        cwd=str(dash),
        timeout=60,
        env={**os.environ, "SEAM_RUNS_ROOT": str(REPO / "runs")},
    )
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "").strip().splitlines()
        c.add(
            "board live stream",
            False,
            "the dashboard's stream resolver FAILED TO RUN: "
            + (detail[-1][:160] if detail else f"exit {proc.returncode}"),
        )
        return
    try:
        res = json.loads(proc.stdout)
    except json.JSONDecodeError:
        c.add(
            "board live stream",
            False,
            f"resolver returned unparseable output: {proc.stdout[:120]!r}",
        )
        return

    run_dir = res.get("run_dir")
    resolved = res.get("resolved")
    on_disk = res.get("on_disk") or []

    if not run_dir:
        c.add(
            "board live stream",
            True,
            "no run on disk yet — reader seam unverified until a cell has written one",
            blocking=False,
        )
        return

    rel = Path(run_dir).name
    if not on_disk:
        # Pre-launch on a fresh tree. Nothing to disagree about YET.
        c.add(
            "board live stream",
            True,
            f"no live.jsonl under the active run ({rel}) — nothing written yet, seam unverified",
            blocking=False,
        )
        return

    if resolved is None:
        found = (
            Path(on_disk[0]).relative_to(Path(run_dir).parent.parent)
            if len(on_disk)
            else ""
        )
        c.add(
            "board live stream",
            False,
            f"BOARD IS BLIND: {len(on_disk)} live.jsonl on disk under the active run but the "
            f"dashboard resolver found NONE (e.g. .../{found}). The gate wall and the learning "
            "matrix will read 'no live.jsonl yet' for the WHOLE run. Fix "
            "dashboard/sources/_runtime.mjs::liveStreamPath — do NOT launch onto a blind board.",
        )
        return

    if resolved not in on_disk:
        c.add(
            "board live stream",
            False,
            f"resolver returned {resolved!r}, which is not among the {len(on_disk)} stream(s) "
            "actually on disk — reader and writer disagree about WHERE the stream lives.",
        )
        return

    extra = f" ({len(on_disk)} on disk, newest wins)" if len(on_disk) > 1 else ""
    c.add(
        "board live stream",
        True,
        f"reader resolves the harness's own stream{extra}: "
        f"{Path(resolved).relative_to(Path(run_dir))}",
    )


def check_disk(c: Check) -> None:
    usage = shutil.disk_usage(REPO)
    free_gb = usage.free / 1e9
    c.add(
        "disk free",
        free_gb > 10,
        f"{free_gb:.1f} GB free"
        + ("" if free_gb > 10 else " — LOW, a run can fill this"),
        blocking=False,
    )


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Preflight for a benchmark cell (local default, or --cloud)."
    )
    ap.add_argument(
        "--model",
        default="qwen3.6-35b-a3b-bench",
        help="local mode: subject bench alias pinned for the run "
        "(WORKER_MODEL_REGISTRY); --cloud mode: the MODEL HALF of the "
        "'{provider}/{model}' roster key (e.g. deepseek-chat with "
        "--provider deepseek), not a bench alias",
    )
    ap.add_argument(
        "--json",
        action="store_true",
        help="emit the checks as JSON instead of the human table (used by the board)",
    )
    ap.add_argument("--mode", default="off", choices=("off", "on"))
    ap.add_argument(
        "--compact",
        action="store_true",
        help=(
            "Check the readiness of chunk-boundary self-compaction too. The "
            "worker image must actually wire the self-compact plugin in its "
            "opencode config — opencode swallows plugin load errors, so a "
            "broken image is otherwise silent."
        ),
    )
    ap.add_argument("--org", default=None, help="org id (ON cells only)")
    ap.add_argument(
        "--cloud",
        action="store_true",
        help="preflight a direct-to-cloud cell (OrcaRouter) instead of "
        "the local relay proxy",
    )
    ap.add_argument(
        "--provider",
        default=None,
        help="cloud vendor id (e.g. deepseek) — the '{provider}/{model}' "
        "key inside the OrcaRouter provider block. Only used with --cloud.",
    )
    ap.add_argument(
        "--router",
        default="orcarouter",
        help="cloud router id for the composed slug {router}/{provider}/{model} "
        "(default: orcarouter). Only used with --cloud.",
    )
    args = ap.parse_args()

    # Keep module loggers silent (spend_key logs key fingerprints at INFO while
    # resolving): the fingerprint belongs in the check row, never on stderr twice.
    logging.basicConfig(level=logging.CRITICAL)

    if not args.json:
        print("\nBENCH PREFLIGHT  (RUNBOOK §0 + AGENTS.md §2.1)\n")
    c = Check()
    check_ports(c)
    check_identity(c)
    check_image(c)
    check_serve_drive_image(c)
    check_grader_image(c)
    check_grader_resources(c)

    bench_config = spend_key = None
    try:
        sys.path.insert(0, str(REPO))
        from harness import config as bench_config
        from harness import spend_key
    except Exception as exc:  # noqa: BLE001
        c.add("bench config", False, f"cannot import harness: {exc}")

    if args.cloud:
        check_cloud_key(c, spend_key)
        check_cloud_model(c, bench_config, args)
    else:
        check_local_model(c, bench_config, args)
    check_roster_drift(c, bench_config)
    check_control_plane_freshness(c)
    check_self_compact_tool(c, args)
    check_feedback_completeness(c)
    check_run_dir(c, args)
    check_live_stream(c)
    check_disk(c)
    if args.json:
        # The verdict is computed the same way for both renderings — the JSON is
        # a projection of this run, never a second implementation of the rules.
        failures_json = c.blocking_failures
        print(
            json.dumps(
                {
                    "ok": True,
                    "verdict": "no-go" if failures_json else "go",
                    "blocking_failures": len(failures_json),
                    "checks": c.as_rows(),
                },
                indent=None,
            )
        )
        return 1 if failures_json else 0

    c.render()

    failures = c.blocking_failures
    if failures:
        print(
            f"\nNO-GO — {len(failures)} blocking check(s) failed. Resolve the above, re-run.\n"
        )
        return 1

    arm = args.mode
    on_flags = (
        f" --mode on --org {args.org or '<org>'}"
        if args.mode == "on"
        else " --mode off"
    )
    default_router = getattr(bench_config, "DEFAULT_CLOUD_ROUTER", "orcarouter")
    print("\nGO — all blocking checks passed. Launch:\n")
    print(
        "  TS=$(date +%Y%m%dT%H%M%S) && nohup .venv/bin/python scripts/run_cumulative.py \\"
    )
    if args.cloud:
        # Main-parser flags BEFORE the `run` subcommand, mirroring run_cumulative.py
        # argparse; --router is printed only when it differs from the default.
        router_flag = (
            "" if args.router == default_router else f" --router {args.router}"
        )
        print(
            f"    --cloud{router_flag} --provider {args.provider} --model {args.model} run{on_flags} \\"
        )
    else:
        print(f"    --model {args.model} run{on_flags} \\")
    print(f'    < /dev/null > "runs/{arm}-cell-$TS.log" 2>&1 & disown')
    print("\n  `< /dev/null` is MANDATORY (zsh suspends the job on stdin touch).")
    print("  Main-parser flags go BEFORE `run` — argparse exits 2 otherwise.")
    print(
        "  --model must match on EVERY later subcommand or you get 'roster hash drift'.\n"
    )
    print(
        f"  Then:  grep -E 'session_id|attach_cmd' runs/{arm}-cell-<ts>.log | tail -3\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
